# Generated by Django 4.0 on 2022-03-07 18:31

from django.db import migrations, models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchMetric',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_ip', models.GenericIPAddressField()),
                ('hits', models.IntegerField(null=True)),
                ('search_date', models.DateTimeField(auto_now_add=True)),
                ('search_term', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
