version: '3'

volumes:
  meili-search: {}
  pg: {}

services:
  django:
    build: .
    restart: unless-stopped
    volumes:
      - .:/app:z
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000

  db:
    image: postgres
    volumes:
      - pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  meilisearch:
    image: getmeili/meilisearch
    environment:
      - MEILI_MASTER_KEY=TESTKEYLOCAL
    volumes:
      - meili-search:/data.ms
    ports:
      - "7700:7700"
