# Generated by Django 4.0.3 on 2022-04-05 23:13

from django.db import migrations, models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('image_url', models.CharField(default='', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
