# Generated by Django 4.0.3 on 2022-04-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybnb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=7),
        ),
    ]
